FROM continuumio/miniconda3

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install build-essential -y

RUN pip install --upgrade pip setuptools wheel

ADD requirements.txt /prereqs/
RUN pip install -r ./prereqs/requirements.txt

COPY . .

#Ensures python print lines are printed out
ENV PYTHONUNBUFFERED 1

CMD ["python", "promote_pipeline.py"]