FROM continuumio/miniconda3:4.5.12

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y

RUN pip install --upgrade pip setuptools wheel

RUN conda install psutil -y

COPY . .
RUN pip install -r requirements.txt